-- Resource Metadata
fx_version 'cerulean'
game 'gta5'

author 'BorisK'
description 'LegendsRoleplay'


files {
    'data/**/*.meta',
    -- 'data/**/*.xml',
    -- 'data/**/*.dat',
    -- 'data/**/*.ytyp',
    'audioconfig/*',
    'sfx/**/*'
}

data_file 'HANDLING_FILE'            'data/**/handling*.meta'
data_file 'VEHICLE_LAYOUTS_FILE'    'data/**/vehiclelayouts*.meta'
data_file 'VEHICLE_METADATA_FILE'    'data/**/vehicles*.meta'
data_file 'CARCOLS_FILE'            'data/**/carcols*.meta'
data_file 'VEHICLE_VARIATION_FILE'    'data/**/carvariations*.meta'
data_file 'CONTENT_UNLOCKING_META_FILE' 'data/**/*unlocks.meta'
data_file 'PTFXASSETINFO_FILE' 'data/**/ptfxassetinfo.meta'
data_file 'AUDIO_GAMEDATA' 'audioconfig/elegyx_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/elegyx_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_elegyx'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_majimagt'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ariant_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ariant_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ariant'
data_file 'AUDIO_GAMEDATA' 'audioconfig/sultanrsv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/sultanrsv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_v8sultanrs'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_zircoflow'
data_file 'AUDIO_GAMEDATA' 'audioconfig/lfasound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lfasound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lfasound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/r34sound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/r34sound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_r34sound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ftypesound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ftypesound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ftypesound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/f10m5_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/f10m5_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_f10m5'
data_file 'AUDIO_GAMEDATA' 'audioconfig/npolchar_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/npolchar_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_npolchar'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta488f154_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta488f154_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta488f154'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_bnr34ffeng'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/bnr34ffeng_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/bnr34ffeng_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/bnr34ffeng_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_chevroletlt4'
data_file 'AUDIO_GAMEDATA' 'audioconfig/chevroletlt4_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/chevroletlt4_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_k20c'
data_file 'AUDIO_GAMEDATA' 'audioconfig/k20c_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/k20c_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lfasound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/lfasound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lfasound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_mclarenv8'
data_file 'AUDIO_GAMEDATA' 'audioconfig/mclarenv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/mclarenv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_mercm177'
data_file 'AUDIO_GAMEDATA' 'audioconfig/mercm177_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/mercm177_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_musv8'
data_file 'AUDIO_GAMEDATA' 'audioconfig/musv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/musv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_nisgtr35'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/nisgtr35_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/nisgtr35_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/nisgtr35_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_rotary7'
data_file 'AUDIO_GAMEDATA' 'audioconfig/rotary7_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/rotary7_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s55b30'
data_file 'AUDIO_GAMEDATA' 'audioconfig/s55b30_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s55b30_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta023l539'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta023l539_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta023l539_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta028viper'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta028viper_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta028viper_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta032s63b44'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta032s63b44_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta032s63b44_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta076m156'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta076m156_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta076m156_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_taaud40v8'
data_file 'AUDIO_GAMEDATA' 'audioconfig/taaud40v8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/taaud40v8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_tagt3flat6'
data_file 'AUDIO_GAMEDATA' 'audioconfig/tagt3flat6_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/tagt3flat6_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_talam52v10'
data_file 'AUDIO_GAMEDATA' 'audioconfig/talam52v10_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/talam52v10_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_toysupmk4'
data_file 'AUDIO_GAMEDATA' 'audioconfig/toysupmk4_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/toysupmk4_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_urusv8'
data_file 'AUDIO_GAMEDATA' 'audioconfig/urusv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/urusv8_sounds.dat'
data_file 'DLCTEXT_FILE' 'common/dlctext.meta'
data_file 'HANDLING_FILE' 'common/handling.meta'
data_file 'VEHICLE_METADATA_FILE' 'common/vehicles.meta'
data_file 'CARCOLS_FILE' 'common/carcols.meta'
data_file 'VEHICLE_VARIATION_FILE' 'common/carvariations.meta'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta028viper_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta028viper_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta028viper'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta122s58_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta122s58_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta122s58'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta488f154_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta488f154_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta488f154'
data_file 'AUDIO_GAMEDATA' 'audioconfig/tagt3flat6_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/tagt3flat6_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_tagt3flat6'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/kc201m4f82_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/kc201m4f82_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/kc201m4f82_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_kc201m4f82'
data_file 'AUDIO_GAMEDATA' 'audioconfig/kc189gtrnism_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/kc189gtrnism_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_kc189gtrnism'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/kc73pgt3rsakrapovic_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/kc73pgt3rsakrapovic_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/kc73pgt3rsakrapovic_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_kc73pgt3rsakrapovic'
data_file "AUDIO_SYNTHDATA" "audioconfig/mbnzc63eng_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/mbnzc63eng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/mbnzc63eng_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_mbnzc63eng"
data_file "AUDIO_GAMEDATA" "audioconfig/w211_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/w211_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_w211"
data_file "AUDIO_SYNTHDATA" "audioconfig/c30a_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/c30a_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/c30a_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_c30a"
data_file "AUDIO_SYNTHDATA" "audioconfig/lg56hons2k_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg56hons2k_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg56hons2k_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg56hons2k"
data_file 'AUDIO_SYNTHDATA' 'audioconfig/mcp1eng_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/mcp1eng_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/mcp1eng_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_mcp1eng'
data_file "AUDIO_SYNTHDATA" "audioconfig/lg81hcredeye_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg81hcredeye_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg81hcredeye_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg81hcredeye"
data_file "AUDIO_SYNTHDATA" "audioconfig/lamavgineng_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lamavgineng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lamavgineng_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lamavgineng"
data_file "AUDIO_SYNTHDATA" "audioconfig/lg101timcamz28_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg101timcamz28_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg101timcamz28_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg101timcamz28"
